// <auto-generated />
using AuditSeverityModule.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuditSeverityModule.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220822060748_SaveDetailpropertyIDchange")]
    partial class SaveDetailpropertyIDchange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuditSeverityModule.Models.SaveAuditDetails", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("applicationOwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("auditDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("auditId")
                        .HasColumnType("int");

                    b.Property<string>("auditType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectExecutionStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remedialActionDuration")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SaveDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
